#!/bin/bash
DOW=$(date +'%w')
case $DOW in
	"1")DOW="1";;
	"2")DOW="2";;
	"3")DOW="3";;
	"4")DOW="4";;
	"5")DOW="5";;
	"6")DOW="6";;
	"0")DOW="7";;
	*)DOW="idk";;
esac
echo "$DOW.$(date +'%d/%m|%H:%M')"
#:%S')"
