#!/bin/bash
echo "$(cat /sys/class/backlight/nvidia_0/brightness | awk '{ if($1 <= 10) print "󱩎"; else if($1 <= 20) print "󱩏"; else if($1<=30) print "󱩐"; else if($1<=40) print "󱩑"; else if($1<=50) print "󱩒"; else if($1<=60) print "󱩓"; else if($1<=70) print "󱩔"; else if($1<=80) print "󱩕"; else if($1<=90) print "󱩖"; else if($1<=100) print "󰛨"; }')"
