#!/bin/bash
ID=$( dunstify -p -i "$DESKENV/files/me.png" "ping" "request sent" )
START=$(date +%s.%3N)
dunstify -r $ID -i "$DESKENV/files/me.png" "pong" "$(curl -s -o /dev/null https://archlinux.org && echo ok || echo err), $(echo "$(date +%s.%3N) - $START" | bc | tr "." "\0")ms"
