#!/bin/bash
xset m 1/1 1
java -jar "$DESKENV/scripts/bggen.jar" "$DESKENV/files" & #todo
cd $DESKENV/scripts/drpc && ./run 2> /dev/null &
picom &
dunst &
dwmblocks &
xbacklight -set 75 -time 0 -steps 1
exec dwm
